### PR TITLE
Close issues

### LINKED ISSUE #36: Auto-lock any issues added to this repo by people with write access
When an issue is added by someone with write access, it should automatically be locked and this should be pasted at the top of the issue.

```
_This issue outlines an Exercism project. As with all issues in the `exercism/wip` repo, this is an internal issue restricted to the core team. If you have something you need to discuss on this please open an issue at github.com/exercism/exercism._

---

```

### PR DESCRIPTION
**Pull request by kntsoriano**
Closes https://github.com/exercism/wip/issues/36, https://github.com/exercism/wip/issues/34.

Screencast: https://www.loom.com/share/f3a926e519424c9a995cb5fc091bce41

In the future, we'll setup a separate repository for our action in order for it to be used by our other repositories.

### CODE REVIEW

**Review by iHiD — CHANGES_REQUESTED** [review]
See other comment.

**Comment by iHiD** [comment]
@kntsoriano OK, this is a great start. I have three main areas of comments:

1) I think we should actually fill out things like the README.md and delete the boilerplate stuff.
2) We have an https://github.com/exercism/github-actions repo. I think we should put the main action code there so we can share it across other repos too (like you suggested).
3) I think you've slightly misinterpreted #36 and #34. (I might be wrong with this so just tell me if I've misunderstood what you did). I'll think we need to address the ff:

- If someone **has** `write` permission (not `admin` permission, which is what I think you have atm), and they create the issue, then the issue should be **locked**, and the message you have  currently (from #36) should be posted.
- If someone **does not** have `write` permission, and they create the issues, then the issue should be **closed** with the message from #34

I'm not sure if we want two Actions for this (allows us to just specify one functionality in other repos), or one Action that does both (probably more efficient). I'll leave that up to you.

**Comment by kntsoriano** [comment]
Sorry about that, I misinterpreted. I'll start work on this after I've finished up with the changelog.

**Comment by iHiD** [comment]
No probs, dude :)

**Pull request closed without merging**
